Development
DenisCuencaBrex/each-method pull request #2
Opened 2019-06-06 23:00 UTC by DenisCuencaBrex

2019-06-07 12:41 UTC, mcrd25 requested changes
# Good job! 👍 All tests run fine and there are no errors in your test files. However, can't give you the go-ahead  to merge to master just yet 😢 

- **Since the name of this repository and files does not correctly represent what the project is about, it is about enum methods not only the each method.**
- **Your README.md should reflect what I mentioned above, right not it seems like only your each method is being tested, which is not the case**
- **Concerning tests... while you have technically written tests for all of the 9 enumerable methods you implemented there were not extensive and there are improvements that can be made to have it done the "Ruby Way". Here are things I'd like you to do:**
  - It is best practice to use `let` for storing test variables. For example you use [3, 4, 10, 2, 6, 9]: you can define it before the individual method tests like so `let(:test_array1) { [3, 4, 10, 2, 6, 9] } and use that variable instead of [3, 4, 10, 2, 6, 9] in each test that you'd like to use it. Please do this for all testing variables
  - Not all tests are not exhaustive enough for me. You currently have tests like the following:
     ```ruby
     describe "#my_each" do
        it "Returns each element of an array" do
        expect([3, 4, 10, 2, 6, 9].my_each {|x| x }).to eql([3, 4, 10, 2, 6 ,9])
        end
     end
    ````   

    **What I would like you to do is for each method have a describe block with multiple tests, as there are many conditions you can test for any one method.For example, with my each you may write**

    ```ruby
      describe '#each' do
        it 'returns the original array when no output' do
          expect(test_array1.my_each { test_block }).to eq(exepected_result1)
        end
       # you test our standard output as well
        it 'prints result to stdout from block calculation i * 2' do
          expect { test_array1.my_each { |i| print i * 2 } }.to output(/246/).to_stdout
        end
       # check your enumerable method gives same result as official counterpart
       # you can do multiple it statements as well
        it 'all above-mentioned tests match the official enumerable method counterpart' do
          expect(test_array1.my_each { test_block }).to eq(test_array1.each { test_block })
        end
      end
    ```

     **Now, this is only an example, but hopefully, it can give you an idea of things you can test. In my example, I even had the test_block as a variable which would have been defined something like ` let(:test_block) { proc { ||x| x } }` for your original test case.
With all of this being said, please try and add more exhaustive tests. the tests as they right now do not necessarily tell me the code works as it should.
Try to be creative.**

    Some things you can think of:
      - What happens when no block is passed your methods
      - What about those that expect 

- **Implement tests for your `multiply_els` it'd give you more practice with testing**


**With all I've said, you guys have done a fantastic job so far! As it stands I need you guys to particularly try using let blocks for testing and try not to have too many hardcoded values but rather use variables.**

***If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me on and connect with me on my social media.***

**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

2019-06-07 12:41 UTC, mcrd25 commented on spec/my_each_spec.rb
> +        describe "#my_map" do
fix indentation here

2019-06-07 12:41 UTC, mcrd25 commented on spec/my_each_spec.rb
> +        expect([3, 4, 10, 2, 6, 9].my_each {|x| x }).to eql([3, 4, 10, 2, 6 ,9])
Fix indentation here

2019-06-09 00:54 UTC, DenisCuencaBrex commented on spec/my_each_spec.rb
> +        describe "#my_map" do
done!

2019-06-09 00:54 UTC, DenisCuencaBrex commented on spec/my_each_spec.rb
> +        expect([3, 4, 10, 2, 6, 9].my_each {|x| x }).to eql([3, 4, 10, 2, 6 ,9])
done!

2019-06-10 12:33 UTC, mcrd25 requested changes
# As you can tell I had a couple of issues with your tests and custom methods... so unfortunately you cannot 🚀 just yet 😢 

**Please address review comments and take your time... you may need to refactor original methods... This is all to help you so I hope you do not get too frustrated with the changes.**

**Keep your head up 😄!**

***If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media.***

**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

2019-06-10 12:33 UTC, mcrd25 commented on my_each.rb
> -        yield(self[i]) if block_given?
Hey, wondering why you removed block_given line. Good to test if a block is given. Hope you correct in future....

Now I know I'm supposed to review the tests but I am trying to understand some of your choices in changing some of your original methods.

2019-06-10 12:33 UTC, mcrd25 commented on spec/my_each_spec.rb
> +            expect(array.my_each_with_index {|x, index| index}).to eql([0,1,2,3])
actually, while your method returns [0,1,2,3] it is supposed to return [1,2,3,4]. 

each_wtih_index is supposed to return original array unless not given, then it returns enumerator.

If you test like the following:
`expect(array.my_each_with_index {|x, index| index}).to eql(array.each_with_index {|x, index| index})` it would fail


However if you test like the following, by testing output the test would pass and it would have an accurate expectation:
```ruby
it "Returns the index of each element in the array" do
  expect{array.my_each_with_index {|x, index| print index}}.to output(/0123/).to_stdout
end
```

2019-06-10 12:33 UTC, mcrd25 commented on spec/my_each_spec.rb
> +            expect(empty_hash.my_select {|key, val| value > 2}).to eql([])
Please correct this test and your resulting method code, you should expect an empty hash as opposed to empty array...

if you run following test or test it irb you'd have better idea:
`expect(empty_hash.my_select {|key, val| value > 2}).to eql(empty_hash.select {|key, val| value > 2})`

2019-06-10 12:33 UTC, mcrd25 commented on spec/my_each_spec.rb
> +            expect(array.my_any?{block}).to eql(array.my_any?{block})
did you mean `expect(array.my_any?{block}).to eql(array.any?{block})` ?

Heads up:

You'd have to do some refactoring of your code because the correct test actually fails.

Please... if you need help message me on slack and we can have a chat

2019-06-10 12:33 UTC, mcrd25 commented on spec/my_each_spec.rb
> +            expect(array.my_all?{block}).to eql(array.my_all?{block})
This will always pass even if there is an error because you are testing the results of your own method against results of your own method. Did you mean following? 
```ruby
expect(array.my_all?{block}).to eql(array.all?{block})
```

2019-06-10 12:33 UTC, mcrd25 commented on spec/my_each_spec.rb
> +            expect(array.my_none?{block}).to eql(array.my_none?{block})
Again... same issue as with my_any? and my_all? you are always gonna get this to pass even when wrong.

Should not pass the expected result to against result of what you are testing. Should be:
`expect(array.my_none?{block}).to eql(array.none?{block})`

Also... when corrected.. test fails. Would have to refactor original method

2019-06-10 12:33 UTC, mcrd25 commented on spec/my_each_spec.rb
> +            expect(hash1.my_none? {|key, val| val.length > 2}).to eql(true)
This is supposed to be equal to false because at least one of them does have length of more than 2...Have to amend original method...

Please remember, you are not to refactor tests but the method. Changing the test to expect wrong value does not make the method work.

Please remember.. I am here to help! contact me 😄

2019-06-10 12:33 UTC, mcrd25 commented on spec/my_each_spec.rb
> +            expect(array.my_inject {|a, b| a + b}).to eql(11)
Expected value should be 10 yet your method returns 11.

Must refactor code.

check original inject method in irb etc to see what it gives compared to your my_inject

2019-06-10 15:38 UTC, DenisCuencaBrex commented
Hi @mcrd25 , how are you? I recently send a code review for my enumerable methods testing project, i already refactor some code but i have some question about procs, because i cant pass any test with the my_all?, my_any? and my_none? functions when i sumbited the first enumerable methods project it’s says that the only one who accept procs should be my_map, im wrong? please help me

the other problems were fixed already

2019-06-10 15:38 UTC, DenisCuencaBrex commented on my_each.rb
> -        yield(self[i]) if block_given?
done!

2019-06-10 15:39 UTC, DenisCuencaBrex commented on spec/my_each_spec.rb
> +            expect(array.my_each_with_index {|x, index| index}).to eql([0,1,2,3])
done, now i get the correct output

2019-06-10 15:39 UTC, DenisCuencaBrex commented on spec/my_each_spec.rb
> +            expect(empty_hash.my_select {|key, val| value > 2}).to eql([])
done

2019-06-10 15:39 UTC, DenisCuencaBrex commented on spec/my_each_spec.rb
> +            expect(hash1.my_none? {|key, val| val.length > 2}).to eql(true)
done

2019-06-10 15:39 UTC, DenisCuencaBrex commented on spec/my_each_spec.rb
> +            expect(array.my_inject {|a, b| a + b}).to eql(11)
done

2019-06-10 16:31 UTC, DenisCuencaBrex commented
Hi @mcrd25 , how are you? I already refactor some code but i have some question about procs, because i cant pass any test with the my_all?, my_any? and my_none? functions when i sumbited the first enumerable methods project it’s says that the only one who accept procs should be my_map, im wrong? please help me

the other problems were fixed already

2019-06-12 08:57 UTC, mcrd25 approved these changes
# Yay! We can finally merge to master! 🎊 🚀 

**DID A GREAT JOB IMPLEMENTING THE CHANGES!**


***If you have any questions, now or in the future, do not hesitate to contact me on social media or on slack and I will be glad to chat with you.***
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

😄

2019-06-12 08:57 UTC, mcrd25 commented on spec/my_each_spec.rb
> +            expect(array.my_each{ block }).to eql(array)
It would also be accurate to write it like so `expect(array.my_each(&block)).to eql(array)` since you are calling block explicitly

Could do this for all occurrences of similar situation if you so wish to

2019-06-12 08:57 UTC, mcrd25 commented on .rspec
> +--require spec_helper
you can also add --color (if not windows os) and --format doc (for good documentation of displayed test results in console, especially useful for failing tests)

2019-06-12 08:57 UTC, mcrd25 commented on .rspec
> +--require spec_helper
On separate lines of course!

2019-06-12 09:02 UTC, DenisCuencaBrex commented on .rspec
> +--require spec_helper
oh that's great, i didn't know that, thank you so much for review our project

2019-06-12 09:02 UTC, merged